#!/usr/bin/env python3

#MIT License
#
#Copyright (c) 2021 Sloobot
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.

import os

os.system("printf '\033]2;Bark Toolkit\a'")

import argparse
import sys
import signal

def signal_handler(signal, frame):
    A = '\033[1;33m'
    W = '\033[0m'
    E = '\033[0m'
    print(A+'\n[!]'+W+' Attack completed.'+E)
    os._exit(0)


def main():
	parser = argparse.ArgumentParser()
	parser.add_argument("--target", type = str, metavar = "<IP:port/URL/phone>",
					help = "Target IP:port, URL or phone.")
	parser.add_argument("--tool", type = str, metavar = "[SMS|NTP|TCP|UDP|SYN|POD|SLOWLORIS|MEMCACHED|HTTP|NJRAT]",
					help = "Attack tool.")
	parser.add_argument("--timeout", type = int, default = 10, metavar = "<timeout>",
					help = 'Timeout in secounds.')
	parser.add_argument("--threads", type = int, default = 3, metavar = "<threads>",
					help = "Threads count.")
	parser.add_argument("-u", "--update", action='store_true', dest="update", help = "Update Bark Toolkit.")
	parser.add_argument("--version", action='store_true', dest="version", help = "Show Quack Bark version.")

	# Get args
	args = parser.parse_args()
	threads = args.threads
	time = args.timeout
	method = str(args.tool).upper()
	target = args.target

	if method == "NTP":
		signal.signal(signal.SIGINT, signal_handler)
		import tools.addons.clean
		import tools.addons.logo
		from tools.L4.ntp import NTP_ATTACK
		NTP_ATTACK(threads, time, target)
		
	elif args.update:
		os.system("chmod +x bin/Bark && bin/Bark -u")
		sys.exit()

	elif args.version:
		print("")
		os.system("cat banner/banner.txt")
		print("")
		print("Bark Toolkit v1.0")
		sys.exit()

	elif method == "SYN":
		signal.signal(signal.SIGINT, signal_handler)
		import tools.addons.clean
		import tools.addons.logo
		from tools.L4.syn import SYN_ATTACK
		SYN_ATTACK(threads, time, target)

	elif method == "TCP":
		signal.signal(signal.SIGINT, signal_handler)
		import tools.addons.clean
		import tools.addons.logo
		from tools.L4.tcp import TCP_ATTACK
		TCP_ATTACK(threads, time, target)

	elif method == "POD":
		signal.signal(signal.SIGINT, signal_handler)
		import tools.addons.clean
		import tools.addons.logo
		from tools.L4.pod import POD_ATTACK
		POD_ATTACK(threads, time, target)

	elif method == "NJRAT":
		signal.signal(signal.SIGINT, signal_handler)
		import tools.addons.clean
		import tools.addons.logo
		from tools.L4.njrat import NJRAT_ATTACK
		NJRAT_ATTACK(threads, time, target)

	elif method == "UDP":
		signal.signal(signal.SIGINT, signal_handler)
		import tools.addons.clean
		import tools.addons.logo
		from tools.L4.udp import UDP_ATTACK
		UDP_ATTACK(threads, time, target)

	elif method == "HTTP":
		signal.signal(signal.SIGINT, signal_handler)
		import tools.addons.clean
		import tools.addons.logo
		from tools.L7.http import HTTP_ATTACK
		HTTP_ATTACK(threads, time, target)

	elif method == "SLOWLORIS":
		signal.signal(signal.SIGINT, signal_handler)
		import tools.addons.clean
		import tools.addons.logo
		from tools.L7.slowloris import SLOWLORIS_ATTACK
		SLOWLORIS_ATTACK(threads, time, target)
	
	elif method == "MEMCACHED":
		signal.signal(signal.SIGINT, signal_handler)
		import tools.addons.clean
		import tools.addons.logo
		from tools.L4.memcached import MEMCACHED_ATTACK
		MEMCACHED_ATTACK(threads, time, target)

	elif method == "SMS":
		signal.signal(signal.SIGINT, signal_handler)
		import tools.addons.clean
		import tools.addons.logo
		from tools.SMS.main import SMS_ATTACK
		SMS_ATTACK(threads, time, target)

	else:
		parser.print_help()

if __name__ == '__main__':
	main()
